/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DescriptionDialog: typeof import('./components/DescriptionDialog.vue')['default']
    NewsDetailsDialog: typeof import('./components/NewsDetailsDialog.vue')['default']
    NewsTableFooter: typeof import('./components/NewsTableFooter.vue')['default']
    NewsTableHeader: typeof import('./components/NewsTableHeader.vue')['default']
    NewsTableTopBar: typeof import('./components/NewsTableTopBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Table: typeof import('./components/Table.vue')['default']
    TempTable: typeof import('./components/TempTable.vue')['default']
    Test: typeof import('./components/Test.vue')['default']
  }
}
