/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DescriptionDialog: typeof import('./components/DescriptionDialog.vue')['default']
    DynamicContentForm: typeof import('./components/DynamicContentForm.vue')['default']
    FieldDate: typeof import('./components/fields/FieldDate.vue')['default']
    FieldEditor: typeof import('./components/fields/FieldEditor.vue')['default']
    FieldEmail: typeof import('./components/fields/FieldEmail.vue')['default']
    FieldEmbed: typeof import('./components/fields/FieldEmbed.vue')['default']
    FieldFiles: typeof import('./components/fields/FieldFiles.vue')['default']
    FieldHeader: typeof import('./components/fields/FieldHeader.vue')['default']
    FieldImage: typeof import('./components/fields/FieldImage.vue')['default']
    FieldMultiEditor: typeof import('./components/fields/FieldMultiEditor.vue')['default']
    FieldSimpleEditor: typeof import('./components/fields/FieldSimpleEditor.vue')['default']
    FieldSlider: typeof import('./components/fields/FieldSlider.vue')['default']
    FieldTable: typeof import('./components/fields/FieldTable.vue')['default']
    FieldText: typeof import('./components/fields/FieldText.vue')['default']
    FieldTextArea: typeof import('./components/fields/FieldTextArea.vue')['default']
    FieldUnorderedList: typeof import('./components/fields/FieldUnorderedList.vue')['default']
    FieldVideo: typeof import('./components/fields/FieldVideo.vue')['default']
    FieldYoutubeId: typeof import('./components/fields/FieldYoutubeId.vue')['default']
    NewsDetailsDialog: typeof import('./components/NewsDetailsDialog.vue')['default']
    NewsTableFooter: typeof import('./components/NewsTableFooter.vue')['default']
    NewsTableHeader: typeof import('./components/NewsTableHeader.vue')['default']
    NewsTableTopBar: typeof import('./components/NewsTableTopBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
